version: 2.1

jobs:
  test_py3:
    docker:
      - image: cyclus/cycamore:latest
    steps:
      - checkout
      - run: pip install -U pytest
      - run: pytest

workflows:
  testing:
    jobs:
      - test_py3
